; FILE AUTO GENERATED BY COMPILER
; --------------------
; Translator tpc -> asm
;
; authors : Elliott FALGUEROLLE & Antonin JEAN

section .bss
section .bss
global_vars: resb 12
section .text
extern printInt
global _start

_start:
	mov rbp, rsp
	sub rsp, 11
	push 84
	pop rax
	mov byte [rbp-10], al
	push 87
	pop rax
	mov byte [rbp-9], al
	push 76
	pop rax
	mov byte [rbp-8], al
	pop rax
	mov dword [global_vars+0], eax
	push 0
	pop rax
	mov dword [global_vars+8], eax
	push 0
	pop rax
	mov dword [global_vars+4], eax
	push 1
	mov rax, 60
	mov rdi, 0
	syscall

updateTurn:
	; Function Header
	push rbp
	mov rbp, rsp
	push rbx

	sub rsp, 8
	mov eax, dword [global_vars+4]
	push rax
	push 1
	pop rbx
	pop rax
	add rax, rbx
	push rax
	mov eax, dword [global_vars+0]
	push rax
	pop rbx
	pop rax
	xor rdx, rdx
	idiv rbx
	push rax
	pop rax
	mov dword [global_vars+4], eax

	; Function Footer
	pop rbx
	mov rsp, rbp
	pop rbp
	ret


