; FILE AUTO GENERATED BY COMPILER
; --------------------
; Translator tpc -> asm
;
; authors : Elliott FALGUEROLLE & Antonin JEAN

section .data
section .text
extern printInt
global _start

main:
	add rsp, 8
	pop dword [rbp-0]
	; End of Program: Print -1 as Fine-Output
	mov rdi, -1
	call printInt
	mov rax, 60
	mov rdi, 0
	syscall

ghost:
; Function Header : refresh rbp
	push rbp
	mov rbp, rsp

	add rsp, 0

; Function Footer : refresh rbp
	mov rsp, rbp
	pop rbp
	ret


