/**
 * @author Antonin JEAN
 * @email ofghanirre@gmail.com
 * @create date 2022-04-05 16:48:52
 * @modify date 2022-04-05 16:48:52
 * @desc Src file related to asm translation
 */

#include "../inc/translator.h"

#define SIZE_INT "dd"
#define SIZE_CHAR "db"

#define __ASM_PATTERN_HEADER \
    "; FILE AUTO GENERATED BY COMPILER\n"                   \
    "; --------------------\n"                              \
    "; Translator tpc -> asm\n"                             \
    ";\n"                                                   \
    "; authors : Elliott FALGUEROLLE & Antonin JEAN\n\n"

#define __ASM_PATTERN_MAIN_FOOTER\
    "\t; End of Program: Print -1 as Fine-Output\n"           \
    "\tmov rdi, -1\n"                                       \
    "\tcall printInt\n"                                     \
    "\tmov rax, 60\n"                                         \
    "\tmov rdi, 0\n"                                          \
    "\tsyscall"

#define __ASM_PATTERN_FNC_HEADER \
    "; Function Header : refresh rbp\n" \
    "\tpush rbp\n" \
    "\tmov rbp, rsp\n\n"

#define __ASM_PATTERN_FNC_FOOTER \
    "\n; Function Footer : refresh rbp\n" \
    "\tmov rsp, rbp\n" \
    "\tpop rbp\n" \
    "\tret\n\n"

#define __ASM_FUNCTION_IDENT "\t"

FILE * asm_file = NULL;

FILE * getFile() { return asm_file; }

void __initAsmFile(const char * name, programSymbolTables symbolTabs, Node* tree) {
    char filename[256] = "\0";
    sprintf(filename, "%s.asm", name);
    asm_file = fopen(filename, "w");
    if (!asm_file) raiseError("__initAsmFile : asm_file failed at creation");
    fprintf(asm_file, __ASM_PATTERN_HEADER);
    initGlobalVariables(symbolTabs);
    initTextSection(symbolTabs);  
    initFunctions(symbolTabs);
    fclose(asm_file);
}

void initTextSection(programSymbolTables symbolTabs) {
    fprintf(asm_file, "section .text\nextern printInt\n");
    if (findHashElem(symbolTabs.globals, "main") != NULL)
        fprintf(asm_file, "global _start\n");
    fprintf(asm_file, "\n");

}

void initGlobalVariables(programSymbolTables symbolTabs) {
    HashElem* el;
    int amount = symbolTabs.globals.elemAmount;
    HashElem ** elements = HashTableValues(&(symbolTabs.globals));
    int totalOffset = 0;
    fprintf(asm_file, "section .data\n");
    for (int i = 0; i < amount; i++) {
        el = elements[i];
        if (el->h_val.type != _type_function) {
            el->h_val.pileOffset = totalOffset;
            totalOffset += el->h_val.val.size;
            fprintf(asm_file, "%s: %s 0\n", el->h_key, 
                el->h_val.type == _type_char ? SIZE_CHAR : SIZE_INT);
        }
    }
    free(elements);
}


void initMain(programSymbolTables symbolTabs) {
    fprintf(asm_file, "_start:\n");
    fprintf(asm_file, "%s\n\n", __ASM_PATTERN_MAIN_FOOTER);
}


void initFunctionVariables(programSymbolTables symbolTabs, functionSymbolTables* func) {
    HashElem* el;
    int totalOffset = 0;
    int parAmount = func->parameters.elemAmount;
    HashElem ** elements = HashTableValues(&(func->parameters));
    for (int i = 0; i < parAmount; i++) {
        el = elements[i];
        el->h_val.pileOffset = totalOffset;
        totalOffset -= el->h_val.val.size;
        //todo, set parameter variables to their values
    }
    free(elements);
    int varAmount = func->values.elemAmount;
    elements = HashTableValues(&(func->values));
    for (int i = 0; i < varAmount; i++) {
        el = elements[i];
        el->h_val.pileOffset = totalOffset;
        totalOffset -= el->h_val.val.size;
    }
    free(elements);
    fprintf(asm_file, "\tadd rsp, %i\n", totalOffset);
}

void initFunctions(programSymbolTables symbolTabs) {
    functionSymbolTables* func = symbolTabs.functions;
    while (func != NULL) {
        if (strcmp(func->name, "main") == 0)
            initMain(symbolTabs);
        else {
            fprintf(asm_file, "%s:\n", func->name);
            fprintf(asm_file, "%s", __ASM_PATTERN_FNC_HEADER);
            initFunctionVariables(symbolTabs, func); 
            //initFunctionBody()
            fprintf(asm_file, "%s", __ASM_PATTERN_FNC_FOOTER);    
        }
        func = func->next;
    }
}

