/**
 * @author Antonin JEAN
 * @email ofghanirre@gmail.com
 * @create date 2022-04-05 16:48:52
 * @modify date 2022-04-05 16:48:52
 * @desc Src file related to asm translation
 */

#include "../inc/translator.h"


#define __ASM_PATTERN_HEADER \
    "; FILE AUTO GENERATED BY COMPILER\n"                   \
    "; --------------------\n"                              \
    "; Translator tpc -> asm\n"                             \
    ";\n"                                                   \
    "; authors : Eliott FALGUEROLLE & Antonin JEAN\n\n"     \
    "section .data\n"                                       \
    "section .text\n"                                       \
    "extern printInt\n"                                     \
    "global _start\n"                                       \
    "_start:\n"                                             \

#define __ASM_PATTERN_FOOTER\
    "; End of Program: Print -1 as Fine-Output\n"           \
    "\tmov rdi, -1\n"                                       \
    "\tcall printInt\n"                                     \
    "mov rax, 60\n"                                         \
    "mov rdi, 0\n"                                          \
    "syscall"

FILE * asm_file = NULL;

FILE * getFile() { return asm_file; }

void __initAsmFile(const char * name) {
    char filename[256] = "\0";
    sprintf(filename, "%s.asm", name);
    asm_file = fopen(filename, "w");
    if (!asm_file) raiseError("__initAsmFile : asm_file failed at creation");
    
    fprintf(asm_file, __ASM_PATTERN_HEADER);
    fprintf(asm_file, __ASM_PATTERN_FOOTER);
}



